### ISSUE TITLE
fix: Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by juno7803** [sopt-makers/sopt-internal-frontend#44]
서버쪽에서 생성하는 ui와  클라에서 그리는 ui가 다르다고 에러가 내려오는 문제

**Comment by Tekiter** [comment]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/36122585/192201429-d0d61c30-ca11-4425-a194-7468dce8b2b9.png">

현재 저는`yarn dev`로 실행했을 때 hydration에러로 어떤 페이지도 볼 수 없네요.

**Comment by ingong** [comment]
hydration issue를 아직 해결 못하셨다면 [stackoverflow 글](https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render) 을 참고해보셔도 좋을 것 같아요! 
저희 공홈 프로젝트도 인수인계받았을 때 dev 모드로 실행하면 해당 에러가 뜨더라구요.

**Comment by juno7803** [comment]
@ingong 감사합니다 🥰 요거 이제 확인중인데 주신 자료도 참고해볼게요 ㅎㅎ
