### ISSUE TITLE
chore: ESLint 룰 추가, 커밋 메시지 린트 수정

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-internal-frontend#60]
### ESLint 룰 추가
자꾸 import 해놓고 안 쓰는 것들을 지나쳐서.. [@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars) 추가하려고 합니다!

하는 김에 아예 typescript-eslint 플러그인을 recommended로 추가하면 좋을 것 같은데, 슬쩍 해보니까 지금 있는 코드에서 걸리는 룰들 꽤 있더라구요
일단 그런 것들은 다 하나하나 off 할게요!

### 커밋 메시지 린트 수정
안되는 케이스가 있어서 해결

## ✅ To Do List 

- [ ] ESLint 룰 추가
- [ ] 커밋 메시지 린트 수정

**Comment by Tekiter** [comment]
추가로 import 문 깔끔하게 하기 위해서 `eslint-plugin-simple-import-sort` 적용하는건 어때!

**Comment by NamJwong** [comment]
@Tekiter 저는 좋습니다!

**Comment by juno7803** [comment]
@Tekiter 혹시 그거 쓸때 그룹핑 룰 같은것도 적용해서 썼었어?
